# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth' 
pod 'GoogleSignIn', '~> 4.4.0'
pod 'Firebase/Database'


target 'MiRuta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'
pod 'GooglePlaces'

   
  # Pods for MiRuta

  target 'MiRuta-tvOSTests' do
    inherit! :search_paths
    # Pods for testing


   end


  target 'MiRutaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MiRuta-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiRuta-tvOS

end
